// Enums for Audio Tài Lộc backend
export enum ServiceBookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentProvider {
  PAYOS = 'PAYOS',
  VNPAY = 'VNPAY',
  MOMO = 'MOMO',
  CASH = 'CASH',
}

export enum ServiceCategory {
  INSTALLATION = 'INSTALLATION',
  MAINTENANCE = 'MAINTENANCE',
  REPAIR = 'REPAIR',
  LIQUIDATION = 'LIQUIDATION',
  RENTAL = 'RENTAL',
  CONSULTATION = 'CONSULTATION',
  DELIVERY = 'DELIVERY',
  OTHER = 'OTHER',
}

export enum ServiceType {
  AUDIO_EQUIPMENT = 'AUDIO_EQUIPMENT',
  HOME_THEATER = 'HOME_THEATER',
  PROFESSIONAL_SOUND = 'PROFESSIONAL_SOUND',
  LIGHTING = 'LIGHTING',
  CONSULTATION = 'CONSULTATION',
  MAINTENANCE = 'MAINTENANCE',
  OTHER = 'OTHER',
}
