// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/chat" | "/dashboard" | "/dashboard/ai" | "/dashboard/analytics" | "/dashboard/backups" | "/dashboard/banners" | "/dashboard/blog" | "/dashboard/bookings" | "/dashboard/bookings/[id]" | "/dashboard/campaigns" | "/dashboard/categories" | "/dashboard/chat" | "/dashboard/contact-info" | "/dashboard/customers" | "/dashboard/email-templates" | "/dashboard/faq" | "/dashboard/inventory" | "/dashboard/messages" | "/dashboard/notifications" | "/dashboard/orders" | "/dashboard/orders/new" | "/dashboard/payments" | "/dashboard/policies" | "/dashboard/products" | "/dashboard/projects" | "/dashboard/promotions" | "/dashboard/reports" | "/dashboard/reviews" | "/dashboard/search" | "/dashboard/services" | "/dashboard/services/types" | "/dashboard/settings" | "/dashboard/site-stats" | "/dashboard/software" | "/dashboard/support" | "/dashboard/technicians" | "/dashboard/testimonials" | "/dashboard/users" | "/kb/articles" | "/kb/articles/[id]/edit" | "/kb/articles/create" | "/login" | "/profile" | "/projects" | "/projects/[slug]"
type AppRouteHandlerRoutes = "/api/admin/kb/articles" | "/api/admin/kb/articles/[id]" | "/api/analytics" | "/api/auth/login" | "/api/bookings" | "/api/bookings/[id]" | "/api/bookings/[id]/status" | "/api/debug-log" | "/api/health" | "/api/inventory" | "/api/orders" | "/api/orders/[id]" | "/api/products" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/toggle-active" | "/api/projects/[id]/toggle-featured" | "/api/services" | "/api/technicians" | "/api/upload" | "/api/users" | "/api/v1/software" | "/api/v1/software/[id]" | "/health"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = "/api/v1/[[...path]]" | "/uploads/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/kb/articles": {}
  "/api/admin/kb/articles/[id]": { "id": string; }
  "/api/analytics": {}
  "/api/auth/login": {}
  "/api/bookings": {}
  "/api/bookings/[id]": { "id": string; }
  "/api/bookings/[id]/status": { "id": string; }
  "/api/debug-log": {}
  "/api/health": {}
  "/api/inventory": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/products": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/toggle-active": { "id": string; }
  "/api/projects/[id]/toggle-featured": { "id": string; }
  "/api/services": {}
  "/api/technicians": {}
  "/api/upload": {}
  "/api/users": {}
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/api/v1/software": {}
  "/api/v1/software/[id]": { "id": string; }
  "/chat": {}
  "/dashboard": {}
  "/dashboard/ai": {}
  "/dashboard/analytics": {}
  "/dashboard/backups": {}
  "/dashboard/banners": {}
  "/dashboard/blog": {}
  "/dashboard/bookings": {}
  "/dashboard/bookings/[id]": { "id": string; }
  "/dashboard/campaigns": {}
  "/dashboard/categories": {}
  "/dashboard/chat": {}
  "/dashboard/contact-info": {}
  "/dashboard/customers": {}
  "/dashboard/email-templates": {}
  "/dashboard/faq": {}
  "/dashboard/inventory": {}
  "/dashboard/messages": {}
  "/dashboard/notifications": {}
  "/dashboard/orders": {}
  "/dashboard/orders/new": {}
  "/dashboard/payments": {}
  "/dashboard/policies": {}
  "/dashboard/products": {}
  "/dashboard/projects": {}
  "/dashboard/promotions": {}
  "/dashboard/reports": {}
  "/dashboard/reviews": {}
  "/dashboard/search": {}
  "/dashboard/services": {}
  "/dashboard/services/types": {}
  "/dashboard/settings": {}
  "/dashboard/site-stats": {}
  "/dashboard/software": {}
  "/dashboard/support": {}
  "/dashboard/technicians": {}
  "/dashboard/testimonials": {}
  "/dashboard/users": {}
  "/health": {}
  "/kb/articles": {}
  "/kb/articles/[id]/edit": { "id": string; }
  "/kb/articles/create": {}
  "/login": {}
  "/profile": {}
  "/projects": {}
  "/projects/[slug]": { "slug": string; }
  "/uploads/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
