"use client"

import { useState, useEffect } from "react"
import { toast } from "sonner"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { apiClient, ApiError } from "@/lib/api-client"
import { useAuth } from "@/lib/auth-context"
import { ImageUpload, ImageWithSEO, normalizeImages, getImageUrls } from "@/components/ui/image-upload"
import { Loader2, Wand2, ChevronUp, ChevronDown } from "lucide-react"

interface AxiosError {
  response?: {
    data?: ApiError;
    status?: number;
    headers?: Record<string, string>;
  };
  request?: unknown;
  message?: string;
}

interface Product {
  id: string
  slug?: string
  name: string
  description?: string | null
  shortDescription?: string | null
  priceCents: number
  originalPriceCents?: number | null
  imageUrl?: string | null
  images?: string[]
  categoryId?: string | null
  brand?: string | null
  model?: string | null
  sku?: string | null
  specifications?: Record<string, unknown>
  features?: string | null
  warranty?: string | null
  weight?: number | null
  dimensions?: string | null
  stockQuantity?: number
  minOrderQuantity?: number
  maxOrderQuantity?: number | null
  tags?: string | null
  metaTitle?: string | null
  metaDescription?: string | null
  metaKeywords?: string | null
  canonicalUrl?: string | null
  featured?: boolean
  isActive?: boolean
  isDigital?: boolean
  downloadUrl?: string | null
  isDeleted?: boolean
  viewCount?: number
  createdAt: string
  updatedAt: string
}

interface Category {
  id: string
  name: string
  slug: string
}

interface ProductFormDialogProps {
  product: Product | null
  open: boolean
  onOpenChange: (open: boolean) => void
  categories: Category[]
  onSuccess: () => void
  defaultIsDigital?: boolean
}

interface ProductFormData {
  name: string
  description: string
  shortDescription: string
  priceCents: number
  originalPriceCents: number
  categoryId: string
  images: ImageWithSEO[]
  brand: string
  model: string
  sku: string
  specifications: Record<string, unknown>
  features: string
  warranty: string
  weight: number
  dimensions: string
  stockQuantity: number
  minOrderQuantity: number
  maxOrderQuantity: number
  tags: string
  metaTitle: string
  metaDescription: string
  metaKeywords: string
  canonicalUrl: string
  featured: boolean
  isActive: boolean
  isDigital: boolean
  downloadUrl: string
}

export function ProductFormDialog({
  product,
  open,
  onOpenChange,
  categories,
  onSuccess,
  defaultIsDigital = false,
}: ProductFormDialogProps) {
  const { } = useAuth()
  const [loading, setLoading] = useState(false)
  const resolvedDefaultIsDigital = Boolean(defaultIsDigital)
  const [formData, setFormData] = useState<ProductFormData>({
    name: '',
    description: '',
    shortDescription: '',
    priceCents: 0,
    originalPriceCents: 0,
    categoryId: '',
    images: [],
    brand: '',
    model: '',
    sku: '',
    specifications: {} as Record<string, unknown>,
    features: '',
    warranty: '',
    weight: 0,
    dimensions: '',
    stockQuantity: 0,
    minOrderQuantity: 1,
    maxOrderQuantity: 0,
    tags: '',
    metaTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: '',
    featured: false,
    isActive: true,
    isDigital: resolvedDefaultIsDigital,
    downloadUrl: ''
  })

  // SEO state
  const [seoData, setSeoData] = useState({
    metaTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: '',
    slug: ''
  })

  const [showSEOSection, setShowSEOSection] = useState(false)

  const [skuError, setSkuError] = useState('')
  const [skuValidating, setSkuValidating] = useState(false)
  const [isAutoGeneratedSku, setIsAutoGeneratedSku] = useState(false)

  // Local state for specs string to allow typing invalid JSON
  const [specsString, setSpecsString] = useState('')

  useEffect(() => {
    if (product) {
      setFormData({
        name: product.name || '',
        description: product.description || '',
        shortDescription: product.shortDescription || '',
        priceCents: product.priceCents || 0,
        originalPriceCents: product.originalPriceCents || 0,
        categoryId: product.categoryId || '',
        images: normalizeImages(Array.isArray(product.images) ? product.images : (product.imageUrl ? [product.imageUrl] : [])),
        brand: product.brand || '',
        model: product.model || '',
        sku: product.sku || '',
        specifications: Array.isArray(product.specifications)
          ? product.specifications.reduce((acc: any, item: any) => ({ ...acc, [item.key]: item.value }), {})
          : product.specifications || {},
        features: product.features || '',
        warranty: product.warranty || '',
        weight: product.weight || 0,
        dimensions: product.dimensions || '',
        stockQuantity: product.stockQuantity || 0,
        minOrderQuantity: product.minOrderQuantity || 1,
        maxOrderQuantity: product.maxOrderQuantity || 0,
        tags: product.tags || '',
        metaTitle: product.metaTitle || '',
        metaDescription: product.metaDescription || '',
        metaKeywords: product.metaKeywords || '',
        canonicalUrl: product.canonicalUrl || '',
        featured: product.featured || false,
        isActive: product.isActive !== undefined ? product.isActive : true,
        isDigital: Boolean(product.isDigital),
        downloadUrl: product.downloadUrl || ''
      })

      // Sync SEO data
      setSeoData({
        metaTitle: product.metaTitle || '',
        metaDescription: product.metaDescription || '',
        metaKeywords: product.metaKeywords || '',
        canonicalUrl: product.canonicalUrl || '',
        slug: product.slug || ''
      })
      setSpecsString(JSON.stringify(
        Array.isArray(product.specifications)
          ? product.specifications.reduce((acc: any, item: any) => ({ ...acc, [item.key]: item.value }), {})
          : product.specifications || {},
        null, 2
      ))
    } else {
      setFormData({
        name: '',
        description: '',
        shortDescription: '',
        priceCents: 0,
        originalPriceCents: 0,
        categoryId: '',
        images: [],
        brand: '',
        model: '',
        sku: '',
        specifications: {},
        features: '',
        warranty: '',
        weight: 0,
        dimensions: '',
        stockQuantity: 0,
        minOrderQuantity: 1,
        maxOrderQuantity: 0,
        tags: '',
        metaTitle: '',
        metaDescription: '',
        metaKeywords: '',
        canonicalUrl: '',
        featured: false,
        isActive: true,
        isDigital: resolvedDefaultIsDigital,
        downloadUrl: ''
      })

      // Reset SEO data
      setSeoData({
        metaTitle: '',
        metaDescription: '',
        metaKeywords: '',
        canonicalUrl: '',
        slug: ''
      })
      setSpecsString('{}')
    }
  }, [product, resolvedDefaultIsDigital])

  // Auto-generate SKU when name is entered for new products
  useEffect(() => {
    const autoGenerateSku = async () => {
      if (!product && formData.name && !formData.sku && !isAutoGeneratedSku) {
        try {
          const response = await apiClient.generateUniqueSku(formData.name)
          const newSku = response.data as string
          setFormData(prev => ({ ...prev, sku: newSku }))
          setIsAutoGeneratedSku(true)
        } catch (error) {
          console.error('Error auto-generating SKU:', error)
          // Don't show error for auto-generation failures
        }
      }
    }

    // Debounce auto-generation
    const timeoutId = setTimeout(autoGenerateSku, 1000)
    return () => clearTimeout(timeoutId)
  }, [formData.name, product, formData.sku, isAutoGeneratedSku])

  // Helper function to remove Vietnamese tones and convert to ASCII-friendly slug
  const removeVietnameseTones = (str: string): string => {
    // Vietnamese character mappings
    const from = 'àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ'
    const to = 'aaaaaaaaaaaaaaaaaeeeeeeeeeeeiiiiiooooooooooooooooouuuuuuuuuuuyyyyyd'

    let result = str.toLowerCase()
    for (let i = 0; i < from.length; i++) {
      result = result.replace(new RegExp(from[i], 'g'), to[i])
    }

    return result
      .replace(/[^a-z0-9\s-]/g, '') // Remove remaining special characters
      .replace(/\s+/g, '-')         // Replace spaces with hyphens
      .replace(/-+/g, '-')          // Replace multiple hyphens with single
      .replace(/^-|-$/g, '')        // Remove leading/trailing hyphens
      .trim()
  }

  // Auto-generate SEO data from product name
  const generateSEOData = () => {
    const baseSlug = removeVietnameseTones(formData.name)

    const newSeoData = {
      metaTitle: formData.name ? `${formData.name} - AudioTailoc` : '',
      metaDescription: formData.shortDescription || formData.description?.substring(0, 160) || '',
      metaKeywords: formData.tags ? formData.tags.split(',').map(tag => tag.trim()).join(', ') : '',
      canonicalUrl: `/san-pham/${baseSlug}`,
      slug: baseSlug
    }

    setSeoData(newSeoData)
    setFormData(prev => ({
      ...prev,
      metaTitle: newSeoData.metaTitle,
      metaDescription: newSeoData.metaDescription,
      metaKeywords: newSeoData.metaKeywords,
      canonicalUrl: newSeoData.canonicalUrl
    }))
  }

  // Update form data when SEO data changes
  const updateFormDataFromSEO = (newSeoData: typeof seoData) => {
    setFormData(prev => ({
      ...prev,
      metaTitle: newSeoData.metaTitle,
      metaDescription: newSeoData.metaDescription,
      metaKeywords: newSeoData.metaKeywords,
      canonicalUrl: newSeoData.canonicalUrl
    }))
  }

  // Handle SEO data changes
  const handleSEOChange = (field: keyof typeof seoData, value: string) => {
    const newSeoData = { ...seoData, [field]: value }
    setSeoData(newSeoData)
    updateFormDataFromSEO(newSeoData)
  }

  // Validate SKU uniqueness
  const validateSku = async (sku: string) => {
    if (!sku.trim() || isAutoGeneratedSku) {
      setSkuError('')
      return
    }

    setSkuValidating(true)
    setSkuError('')

    try {
      const exists = await apiClient.checkSkuExists(sku, product?.id)

      if (exists) {
        setSkuError('SKU này đã tồn tại. Vui lòng chọn SKU khác.')
      } else {
        setSkuError('')
      }
    } catch (error) {
      console.error('Error checking SKU:', error)
      setSkuError('Không thể kiểm tra SKU. Vui lòng thử lại.')
    } finally {
      setSkuValidating(false)
    }
  }

  // Generate unique SKU
  const generateSku = async () => {
    setSkuValidating(true)
    setSkuError('')

    try {
      const baseName = formData.name || 'PROD'
      const response = await apiClient.generateUniqueSku(baseName)
      const newSku = response.data as string

      setFormData(prev => ({ ...prev, sku: newSku }))
      setIsAutoGeneratedSku(true)
      setSkuError('')

      toast.success('Đã tạo SKU tự động: ' + newSku)
    } catch (error) {
      console.error('Error generating SKU:', error)
      setSkuError('Không thể tạo SKU tự động. Vui lòng thử lại.')
      toast.error('Không thể tạo SKU tự động')
    } finally {
      setSkuValidating(false)
    }
  }

  const handleSkuChange = (value: string) => {
    setFormData(prev => ({ ...prev, sku: value }))
    setIsAutoGeneratedSku(false) // Reset auto-generated flag when user manually changes SKU

    // Debounce SKU validation
    const timeoutId = setTimeout(() => validateSku(value), 500)
    // Store timeout ID for cleanup if needed
    return () => clearTimeout(timeoutId)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)

    // Basic validation
    if (!formData.name || !formData.priceCents) {
      toast.error('Vui lòng điền đầy đủ thông tin bắt buộc (tên và giá sản phẩm)')
      setLoading(false)
      return
    }

    // Check SKU validation
    if (skuError) {
      toast.error('Vui lòng sửa lỗi SKU trước khi lưu sản phẩm')
      setLoading(false)
      return
    }

    try {
      // Prepare product data with proper types
      const productData = {
        name: formData.name,
        priceCents: Number(formData.priceCents),
        description: formData.description || undefined,
        shortDescription: formData.shortDescription || undefined,
        originalPriceCents: formData.originalPriceCents ? Number(formData.originalPriceCents) : undefined,
        stockQuantity: Number(formData.stockQuantity) || 0,
        minOrderQuantity: Number(formData.minOrderQuantity) || 1,
        maxOrderQuantity: formData.maxOrderQuantity ? Number(formData.maxOrderQuantity) : undefined,
        categoryId: formData.categoryId || undefined,
        // Map images to simple string array (backend DTO expects string[])
        images: Array.isArray(formData.images)
          ? formData.images.map(img => img.url)
          : [],
        brand: formData.brand || undefined,
        model: formData.model || undefined,
        sku: formData.sku || undefined,
        // Transform specifications object to DTO array format
        specifications: Object.entries(formData.specifications || {}).map(([key, value]) => ({
          key,
          value: String(value)
        })),
        features: formData.features || undefined,
        warranty: formData.warranty || undefined,
        weight: formData.weight ? Number(formData.weight) : undefined,
        dimensions: formData.dimensions || undefined,
        tags: formData.tags || undefined,
        metaTitle: formData.metaTitle || undefined,
        metaDescription: formData.metaDescription || undefined,
        metaKeywords: formData.metaKeywords || undefined,
        canonicalUrl: formData.canonicalUrl || undefined,
        slug: seoData.slug || removeVietnameseTones(formData.name),
        featured: Boolean(formData.featured),
        isActive: Boolean(formData.isActive),
        isDigital: Boolean(formData.isDigital),
        downloadUrl: formData.isDigital
          ? (formData.downloadUrl ? formData.downloadUrl.trim() : undefined)
          : undefined
      }

      if (product) {
        // Update existing product
        await apiClient.updateProduct(product.id, productData)
        toast.success('Cập nhật sản phẩm thành công')
      } else {
        // Create new product
        await apiClient.createProduct(productData)
        toast.success('Thêm sản phẩm mới thành công')
      }

      onSuccess()
      onOpenChange(false)
    } catch (error: unknown) {
      console.error('Failed to save product:', error)

      // More detailed error handling
      let errorMessage = 'Có lỗi xảy ra khi lưu sản phẩm'
      const axiosError = error as AxiosError
      if (axiosError.response) {
        // The request was made and the server responded with a status code
        // that falls out of the range of 2xx
        console.error('Error response data:', axiosError.response.data)
        console.error('Error status:', axiosError.response.status)
        console.error('Error headers:', axiosError.response.headers)

        if (axiosError.response.data && typeof axiosError.response.data === 'object') {
          errorMessage = axiosError.response.data.message || JSON.stringify(axiosError.response.data)
        }
      } else if (axiosError.request) {
        // The request was made but no response was received
        console.error('No response received:', axiosError.request)
        errorMessage = 'Không nhận được phản hồi từ máy chủ'
      } else {
        // Something happened in setting up the request that triggered an Error
        console.error('Error message:', axiosError.message)
        errorMessage = axiosError.message || 'Lỗi khi gửi yêu cầu'
      }

      toast.error(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('vi-VN', {
      style: 'currency',
      currency: 'VND'
    }).format(amount / 100)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {product ? 'Chỉnh sửa sản phẩm' : 'Thêm sản phẩm mới'}
          </DialogTitle>
          <DialogDescription>
            {product ? 'Cập nhật thông tin sản phẩm' : 'Tạo sản phẩm mới trong hệ thống'}
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">Tên sản phẩm *</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                placeholder="Nhập tên sản phẩm"
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="category">Danh mục *</Label>
              <Select
                value={formData.categoryId}
                onValueChange={(value) => setFormData(prev => ({ ...prev, categoryId: value }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Chọn danh mục" />
                </SelectTrigger>
                <SelectContent>
                  {categories.map((category) => (
                    <SelectItem key={category.id} value={category.id}>
                      {category.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Mô tả</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              placeholder="Nhập mô tả sản phẩm"
              rows={3}
            />
          </div>

          {/* Product Details */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="brand">Thương hiệu</Label>
              <Input
                id="brand"
                value={formData.brand}
                onChange={(e) => setFormData(prev => ({ ...prev, brand: e.target.value }))}
                placeholder="Nhập thương hiệu"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="model">Model</Label>
              <Input
                id="model"
                value={formData.model}
                onChange={(e) => setFormData(prev => ({ ...prev, model: e.target.value }))}
                placeholder="Nhập model"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="sku">SKU</Label>
              <div className="flex gap-2">
                <Input
                  id="sku"
                  value={formData.sku}
                  onChange={(e) => handleSkuChange(e.target.value)}
                  placeholder="Nhập SKU hoặc để trống để tự động tạo"
                  className={skuError ? 'border-red-500' : ''}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={generateSku}
                  disabled={skuValidating}
                  className="shrink-0"
                >
                  {skuValidating ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Wand2 className="h-4 w-4" />
                  )}
                </Button>
              </div>
              {skuValidating && <p className="text-sm text-blue-600">Đang tạo SKU...</p>}
              {skuError && <p className="text-sm text-red-600">{skuError}</p>}
              <p className="text-xs text-gray-500">
                Để trống để tự động tạo SKU hoặc click biểu tượng để tạo ngay
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="stockQuantity">Tồn kho</Label>
              <Input
                id="stockQuantity"
                type="number"
                value={formData.stockQuantity}
                onChange={(e) => setFormData(prev => ({
                  ...prev,
                  stockQuantity: parseInt(e.target.value) || 0
                }))}
                placeholder="0"
                min="0"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="price">Giá (VNĐ) *</Label>
              <Input
                id="price"
                type="number"
                value={formData.priceCents / 100}
                onChange={(e) => setFormData(prev => ({
                  ...prev,
                  priceCents: parseInt(e.target.value) * 100 || 0
                }))}
                placeholder="0"
                min="0"
                required
              />
              <p className="text-sm text-muted-foreground">
                Hiển thị: {formatCurrency(formData.priceCents)}
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="originalPrice">Giá gốc (VNĐ)</Label>
              <Input
                id="originalPrice"
                type="number"
                value={formData.originalPriceCents / 100}
                onChange={(e) => setFormData(prev => ({
                  ...prev,
                  originalPriceCents: parseInt(e.target.value) * 100 || 0
                }))}
                placeholder="0"
                min="0"
              />
              {formData.originalPriceCents > 0 && (
                <p className="text-sm text-muted-foreground">
                  Hiển thị: {formatCurrency(formData.originalPriceCents)}
                </p>
              )}
            </div>
          </div>

          <div className="space-y-2">
            <ImageUpload
              label="Hình ảnh sản phẩm"
              value={Array.isArray(formData.images) ? formData.images : []}
              onChange={(images) => {
                setFormData(prev => ({
                  ...prev,
                  images: images
                }))
              }}
              onRemove={(index) => {
                const newImages = [...(formData.images || [])]
                newImages.splice(index, 1)
                setFormData(prev => ({
                  ...prev,
                  images: newImages
                }))
              }}
              placeholder="Kéo thả hình ảnh hoặc nhấn để chọn"
              folder="products"
              maxFiles={10}
              showSEOFields={true}
            />
            <p className="text-sm text-muted-foreground">
              Hỗ trợ: JPG, PNG, WEBP (tối đa 10MB/ảnh). Hover vào hình để thêm Alt Text và Title cho SEO.
            </p>
            {formData.images?.length > 1 && (
              <div className="text-sm text-muted-foreground">
                Đã chọn {formData.images.length} hình ảnh
              </div>
            )}
          </div>

          {/* Additional Details */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="weight">Trọng lượng (kg)</Label>
              <Input
                id="weight"
                type="number"
                step="0.01"
                value={formData.weight}
                onChange={(e) => setFormData(prev => ({
                  ...prev,
                  weight: parseFloat(e.target.value) || 0
                }))}
                placeholder="0"
                min="0"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="dimensions">Kích thước</Label>
              <Input
                id="dimensions"
                value={formData.dimensions}
                onChange={(e) => setFormData(prev => ({ ...prev, dimensions: e.target.value }))}
                placeholder="Ví dụ: 10x20x5 cm"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="features">Tính năng</Label>
            <Textarea
              id="features"
              value={formData.features}
              onChange={(e) => setFormData(prev => ({ ...prev, features: e.target.value }))}
              placeholder="Nhập các tính năng nổi bật"
              rows={2}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="specifications">Thông số kỹ thuật (JSON)</Label>
            <Textarea
              id="specifications"
              value={specsString}
              onChange={(e) => {
                const newValue = e.target.value
                setSpecsString(newValue)
                try {
                  const parsed = newValue ? JSON.parse(newValue) : {}
                  setFormData(prev => ({ ...prev, specifications: parsed }))
                } catch {
                  // Allow invalid JSON while typing, just don't update formData
                }
              }}
              placeholder={`Ví dụ: {"Driver Size": "40mm", "Frequency Response": "20Hz - 20kHz"}`}
              rows={4}
              className="font-mono text-sm"
            />
            <p className="text-xs text-muted-foreground">
              Nhập thông số kỹ thuật dưới dạng JSON
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="warranty">Bảo hành</Label>
            <Input
              id="warranty"
              value={formData.warranty}
              onChange={(e) => setFormData(prev => ({ ...prev, warranty: e.target.value }))}
              placeholder="Ví dụ: 12 tháng"
            />
          </div>

          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="featured"
                checked={formData.featured}
                onChange={(e) => setFormData(prev => ({ ...prev, featured: e.target.checked }))}
                className="h-4 w-4"
                aria-label="Sản phẩm nổi bật"
              />
              <Label htmlFor="featured">Sản phẩm nổi bật</Label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="isActive"
                checked={formData.isActive}
                onChange={(e) => setFormData(prev => ({ ...prev, isActive: e.target.checked }))}
                className="h-4 w-4"
                aria-label="Hoạt động"
              />
              <Label htmlFor="isActive">Hoạt động</Label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="isDigital"
                checked={formData.isDigital}
                onChange={(e) =>
                  setFormData(prev => ({
                    ...prev,
                    isDigital: e.target.checked,
                    downloadUrl: e.target.checked ? prev.downloadUrl : '',
                  }))
                }
                className="h-4 w-4"
                aria-label="Sản phẩm tải về"
              />
              <Label htmlFor="isDigital">Sản phẩm tải về</Label>
            </div>
          </div>

          {formData.isDigital && (
            <div className="space-y-2">
              <Label htmlFor="downloadUrl">Link tải (Google Drive)</Label>
              <Input
                id="downloadUrl"
                value={formData.downloadUrl}
                onChange={(e) => setFormData(prev => ({ ...prev, downloadUrl: e.target.value }))}
                placeholder="https://drive.google.com/file/d/<fileId>/view"
              />
              <p className="text-xs text-muted-foreground">
                Link này sẽ chỉ hiển thị cho khách sau khi PayOS xác nhận thanh toán thành công.
              </p>
            </div>
          )}

          {/* SEO Section */}
          <div className="border-t pt-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-medium">SEO Optimization</h3>
              <div className="flex items-center space-x-2">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={generateSEOData}
                  disabled={!formData.name}
                >
                  <Wand2 className="mr-2 h-4 w-4" />
                  Tự động tạo
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowSEOSection(!showSEOSection)}
                >
                  {showSEOSection ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                  {showSEOSection ? 'Ẩn' : 'Hiện'} SEO
                </Button>
              </div>
            </div>

            {showSEOSection && (
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="metaTitle">Meta Title</Label>
                    <Input
                      id="metaTitle"
                      value={seoData.metaTitle}
                      onChange={(e) => handleSEOChange('metaTitle', e.target.value)}
                      placeholder="Tiêu đề hiển thị trên Google"
                      maxLength={60}
                    />
                    <p className="text-xs text-muted-foreground">
                      {seoData.metaTitle.length}/60 ký tự
                    </p>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="slug">URL Slug</Label>
                    <Input
                      id="slug"
                      value={seoData.slug}
                      onChange={(e) => handleSEOChange('slug', e.target.value)}
                      placeholder="duong-dan-san-pham"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="metaDescription">Meta Description</Label>
                  <Textarea
                    id="metaDescription"
                    value={seoData.metaDescription}
                    onChange={(e) => handleSEOChange('metaDescription', e.target.value)}
                    placeholder="Mô tả ngắn gọn về sản phẩm hiển thị trên Google"
                    rows={2}
                    maxLength={160}
                  />
                  <p className="text-xs text-muted-foreground">
                    {seoData.metaDescription.length}/160 ký tự
                  </p>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="metaKeywords">Meta Keywords</Label>
                  <Input
                    id="metaKeywords"
                    value={seoData.metaKeywords}
                    onChange={(e) => handleSEOChange('metaKeywords', e.target.value)}
                    placeholder="từ khóa, cách nhau bằng dấu phẩy"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="canonicalUrl">Canonical URL</Label>
                  <Input
                    id="canonicalUrl"
                    value={seoData.canonicalUrl}
                    onChange={(e) => handleSEOChange('canonicalUrl', e.target.value)}
                    placeholder="https://yourdomain.com/products/slug"
                  />
                </div>

                {/* SEO Preview */}
                {seoData.metaTitle && (
                  <div className="border rounded-lg p-4 bg-gray-50">
                    <h4 className="text-sm font-medium mb-2">Preview trên Google:</h4>
                    <div className="space-y-1">
                      <div className="text-blue-600 text-lg hover:underline cursor-pointer">
                        {seoData.metaTitle}
                      </div>
                      <div className="text-green-700 text-sm">
                        {seoData.canonicalUrl || 'https://yourdomain.com/products/' + seoData.slug}
                      </div>
                      <div className="text-gray-600 text-sm">
                        {seoData.metaDescription}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={loading}
            >
              Hủy
            </Button>
            <Button type="submit" disabled={loading}>
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              {product ? 'Cập nhật' : 'Tạo sản phẩm'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
