import { Banner } from '@/lib/types';

// Demo data for testing when backend is not available
export const demoBanners: Banner[] = [
  {
    id: '1',
    title: 'Thiết bị âm thanh chuyên nghiệp',
    subtitle: 'Chất lượng vượt trội - Giá cả hợp lý',
    description: 'Khám phá bộ sưu tập thiết bị âm thanh cao cấp với công nghệ hiện đại nhất. Từ loa chuyên nghiệp đến hệ thống mixer đẳng cấp.',
    imageUrl: '/sample-banners/audio-equipment-banner.jpg',
    mobileImageUrl: '/sample-banners/audio-equipment-banner.jpg',
    buttonLabel: 'Khám phá ngay',
    linkUrl: '/products',
    secondaryButtonLabel: 'Tư vấn miễn phí',
    secondaryButtonUrl: '/contact',
    page: 'home',
    position: 1,
    isActive: true,
    stats: '🔥 Hơn 1000+ khách hàng tin tưởng',
    isDeleted: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Dịch vụ thi công âm thanh',
    subtitle: 'Thiết kế - Lắp đặt - Bảo hành',
    description: 'Đội ngũ kỹ thuật viên chuyên nghiệp với nhiều năm kinh nghiệm. Cam kết chất lượng và tiến độ hoàn thành dự án.',
    imageUrl: '/sample-banners/installation-service-banner.jpg',
    mobileImageUrl: '/sample-banners/installation-service-banner.jpg',
    buttonLabel: 'Đặt lịch tư vấn',
    linkUrl: '/service-booking',
    secondaryButtonLabel: 'Xem dự án',
    secondaryButtonUrl: '/du-an',
    page: 'home',
    position: 2,
    isActive: true,
    stats: '⭐ Đánh giá 4.9/5 từ khách hàng',
    isDeleted: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Khuyến mãi tháng 10',
    subtitle: 'Giảm giá lên đến 30%',
    description: 'Ưu đãi hấp dẫn cho tất cả sản phẩm âm thanh. Cơ hội sở hữu thiết bị chất lượng cao với giá tốt nhất trong năm.',
    imageUrl: '/sample-banners/october-sale-banner.jpg',
    mobileImageUrl: '/sample-banners/october-sale-banner.jpg',
    buttonLabel: 'Mua ngay',
    linkUrl: '/promotions',
    secondaryButtonLabel: 'Xem chi tiết',
    secondaryButtonUrl: '/promotions',
    page: 'home',
    position: 3,
    isActive: true,
    stats: '🎯 Có hiệu lực đến 31/10/2025',
    isDeleted: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];
