// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/auth/forgot-password" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/blog" | "/blog/[slug]" | "/booking-history" | "/brands" | "/cart" | "/categories" | "/categories/[slug]" | "/chat" | "/checkout" | "/compare" | "/contact" | "/customer-admin" | "/danh-muc" | "/danh-muc/[slug]" | "/deals" | "/du-an" | "/du-an/[slug]" | "/events" | "/faq" | "/guides" | "/lien-he" | "/login" | "/news" | "/newsletter" | "/order-success" | "/orders" | "/orders/[id]" | "/payment-history" | "/policies" | "/policies/[slug]" | "/privacy" | "/products" | "/products/[slug]" | "/profile" | "/projects" | "/projects/[slug]" | "/promotions" | "/register" | "/report-issue" | "/return-policy" | "/reviews" | "/sale" | "/search" | "/service-booking" | "/service-orders" | "/services" | "/services/[slug]" | "/shipping" | "/shipping-policy" | "/showroom" | "/so-do-trang" | "/software" | "/software/[slug]" | "/stores" | "/support" | "/technical-support" | "/terms" | "/testimonials" | "/track-order" | "/warranty" | "/wishlist"
type AppRouteHandlerRoutes = "/api/health/[[...path]]" | "/api/maps/directions" | "/api/maps/geocode" | "/api/maps/place-detail" | "/api/maps/reverse" | "/api/orders" | "/api/payment/process" | "/api/payment/status" | "/api/payments/payos/create-payment" | "/api/products" | "/api/products/[id]" | "/api/projects" | "/api/projects/featured" | "/api/proxy/ai/chat" | "/api/proxy/services" | "/api/upload/review" | "/api/v1/[...path]" | "/api/v1/ai/chat" | "/api/v1/auth" | "/api/v1/auth/login" | "/api/v1/auth/profile" | "/api/v1/auth/refresh" | "/api/v1/auth/register" | "/api/v1/cart" | "/api/v1/catalog/categories" | "/api/v1/catalog/products" | "/api/v1/catalog/products/recent" | "/api/v1/catalog/products/top-viewed" | "/api/v1/content/banners" | "/api/v1/orders" | "/api/v1/projects" | "/api/v1/services" | "/api/v1/users" | "/api/webhook/payos" | "/apple-touch-icon-precomposed.png" | "/apple-touch-icon.png"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/blog" | "/blog/[slug]" | "/booking-history" | "/cart" | "/categories" | "/categories/[slug]" | "/chat" | "/checkout" | "/contact" | "/customer-admin" | "/danh-muc" | "/danh-muc/[slug]" | "/du-an" | "/lien-he" | "/orders" | "/policies" | "/products" | "/products/[slug]" | "/profile" | "/projects" | "/return-policy" | "/search" | "/services" | "/services/[slug]" | "/support" | "/warranty" | "/wishlist"
type RedirectRoutes = "/categories" | "/categories/[slug]" | "/projects" | "/projects/[slug]"
type RewriteRoutes = "/api/v1/[[...path]]" | "/uploads/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/admin": {}
  "/api/health/[[...path]]": { "path"?: string[]; }
  "/api/maps/directions": {}
  "/api/maps/geocode": {}
  "/api/maps/place-detail": {}
  "/api/maps/reverse": {}
  "/api/orders": {}
  "/api/payment/process": {}
  "/api/payment/status": {}
  "/api/payments/payos/create-payment": {}
  "/api/products": {}
  "/api/products/[id]": { "id": string; }
  "/api/projects": {}
  "/api/projects/featured": {}
  "/api/proxy/ai/chat": {}
  "/api/proxy/services": {}
  "/api/upload/review": {}
  "/api/v1/[...path]": { "path": string[]; }
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/api/v1/ai/chat": {}
  "/api/v1/auth": {}
  "/api/v1/auth/login": {}
  "/api/v1/auth/profile": {}
  "/api/v1/auth/refresh": {}
  "/api/v1/auth/register": {}
  "/api/v1/cart": {}
  "/api/v1/catalog/categories": {}
  "/api/v1/catalog/products": {}
  "/api/v1/catalog/products/recent": {}
  "/api/v1/catalog/products/top-viewed": {}
  "/api/v1/content/banners": {}
  "/api/v1/orders": {}
  "/api/v1/projects": {}
  "/api/v1/services": {}
  "/api/v1/users": {}
  "/api/webhook/payos": {}
  "/apple-touch-icon-precomposed.png": {}
  "/apple-touch-icon.png": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/booking-history": {}
  "/brands": {}
  "/cart": {}
  "/categories": {}
  "/categories/[slug]": { "slug": string; }
  "/chat": {}
  "/checkout": {}
  "/compare": {}
  "/contact": {}
  "/customer-admin": {}
  "/danh-muc": {}
  "/danh-muc/[slug]": { "slug": string; }
  "/deals": {}
  "/du-an": {}
  "/du-an/[slug]": { "slug": string; }
  "/events": {}
  "/faq": {}
  "/guides": {}
  "/lien-he": {}
  "/login": {}
  "/news": {}
  "/newsletter": {}
  "/order-success": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/payment-history": {}
  "/policies": {}
  "/policies/[slug]": { "slug": string; }
  "/privacy": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/profile": {}
  "/projects": {}
  "/projects/[slug]": { "slug": string; }
  "/promotions": {}
  "/register": {}
  "/report-issue": {}
  "/return-policy": {}
  "/reviews": {}
  "/sale": {}
  "/search": {}
  "/service-booking": {}
  "/service-orders": {}
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/shipping": {}
  "/shipping-policy": {}
  "/showroom": {}
  "/so-do-trang": {}
  "/software": {}
  "/software/[slug]": { "slug": string; }
  "/stores": {}
  "/support": {}
  "/technical-support": {}
  "/terms": {}
  "/testimonials": {}
  "/track-order": {}
  "/uploads/[[...path]]": { "path"?: string[]; }
  "/warranty": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/blog": never
  "/blog/[slug]": never
  "/booking-history": never
  "/cart": never
  "/categories": never
  "/categories/[slug]": never
  "/chat": never
  "/checkout": never
  "/contact": never
  "/customer-admin": never
  "/danh-muc": never
  "/danh-muc/[slug]": never
  "/du-an": never
  "/lien-he": never
  "/orders": never
  "/policies": never
  "/products": never
  "/products/[slug]": never
  "/profile": never
  "/projects": never
  "/return-policy": never
  "/search": never
  "/services": never
  "/services/[slug]": never
  "/support": never
  "/warranty": never
  "/wishlist": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
