// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/booking-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking-history">> = Specific
  const handler = {} as typeof import("../../../app/booking-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands">> = Specific
  const handler = {} as typeof import("../../../app/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../../app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/categories/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/categories/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories">> = Specific
  const handler = {} as typeof import("../../../app/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../../app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../../app/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-admin">> = Specific
  const handler = {} as typeof import("../../../app/customer-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/danh-muc/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/danh-muc/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/danh-muc/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/danh-muc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/danh-muc">> = Specific
  const handler = {} as typeof import("../../../app/danh-muc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deals">> = Specific
  const handler = {} as typeof import("../../../app/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/du-an/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/du-an/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/du-an/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/du-an/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/du-an">> = Specific
  const handler = {} as typeof import("../../../app/du-an/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides">> = Specific
  const handler = {} as typeof import("../../../app/guides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/lien-he/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lien-he">> = Specific
  const handler = {} as typeof import("../../../app/lien-he/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../../app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/newsletter">> = Specific
  const handler = {} as typeof import("../../../app/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/order-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-success">> = Specific
  const handler = {} as typeof import("../../../app/order-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../app/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payment-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment-history">> = Specific
  const handler = {} as typeof import("../../../app/payment-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/policies/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/policies/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies">> = Specific
  const handler = {} as typeof import("../../../app/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/promotions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/promotions">> = Specific
  const handler = {} as typeof import("../../../app/promotions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/report-issue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-issue">> = Specific
  const handler = {} as typeof import("../../../app/report-issue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/return-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/return-policy">> = Specific
  const handler = {} as typeof import("../../../app/return-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../../app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sale">> = Specific
  const handler = {} as typeof import("../../../app/sale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/service-booking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-booking">> = Specific
  const handler = {} as typeof import("../../../app/service-booking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/service-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-orders">> = Specific
  const handler = {} as typeof import("../../../app/service-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/services/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shipping-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipping-policy">> = Specific
  const handler = {} as typeof import("../../../app/shipping-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipping">> = Specific
  const handler = {} as typeof import("../../../app/shipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/showroom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/showroom">> = Specific
  const handler = {} as typeof import("../../../app/showroom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/so-do-trang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/so-do-trang">> = Specific
  const handler = {} as typeof import("../../../app/so-do-trang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/software/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/software/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/software/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/software/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/software">> = Specific
  const handler = {} as typeof import("../../../app/software/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/stores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores">> = Specific
  const handler = {} as typeof import("../../../app/stores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/technical-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/technical-support">> = Specific
  const handler = {} as typeof import("../../../app/technical-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/testimonials">> = Specific
  const handler = {} as typeof import("../../../app/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/track-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track-order">> = Specific
  const handler = {} as typeof import("../../../app/track-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warranty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warranty">> = Specific
  const handler = {} as typeof import("../../../app/warranty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wishlist">> = Specific
  const handler = {} as typeof import("../../../app/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/[[...path]]">> = Specific
  const handler = {} as typeof import("../../../app/api/health/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/maps/directions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maps/directions">> = Specific
  const handler = {} as typeof import("../../../app/api/maps/directions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/maps/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maps/geocode">> = Specific
  const handler = {} as typeof import("../../../app/api/maps/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/maps/place-detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maps/place-detail">> = Specific
  const handler = {} as typeof import("../../../app/api/maps/place-detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/maps/reverse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maps/reverse">> = Specific
  const handler = {} as typeof import("../../../app/api/maps/reverse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payment/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/process">> = Specific
  const handler = {} as typeof import("../../../app/api/payment/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payment/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/status">> = Specific
  const handler = {} as typeof import("../../../app/api/payment/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/payos/create-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/payos/create-payment">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/payos/create-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/projects/featured/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/featured">> = Specific
  const handler = {} as typeof import("../../../app/api/projects/featured/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../../app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/proxy/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/ai/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/proxy/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/proxy/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/services">> = Specific
  const handler = {} as typeof import("../../../app/api/proxy/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/review">> = Specific
  const handler = {} as typeof import("../../../app/api/upload/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/ai/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/auth/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/auth/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/cart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/cart">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/cart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/catalog/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/catalog/categories">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/catalog/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/catalog/products/recent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/catalog/products/recent">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/catalog/products/recent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/catalog/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/catalog/products">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/catalog/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/catalog/products/top-viewed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/catalog/products/top-viewed">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/catalog/products/top-viewed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/content/banners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/content/banners">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/content/banners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/orders">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/projects">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/services">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/users">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhook/payos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/payos">> = Specific
  const handler = {} as typeof import("../../../app/api/webhook/payos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/apple-touch-icon-precomposed.png/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/apple-touch-icon-precomposed.png">> = Specific
  const handler = {} as typeof import("../../../app/apple-touch-icon-precomposed.png/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/apple-touch-icon.png/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/apple-touch-icon.png">> = Specific
  const handler = {} as typeof import("../../../app/apple-touch-icon.png/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/blog/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/booking-history/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/booking-history">> = Specific
  const handler = {} as typeof import("../../../app/booking-history/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cart/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../../app/cart/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/categories/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/categories/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/categories/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/categories/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/categories">> = Specific
  const handler = {} as typeof import("../../../app/categories/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/chat/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../../app/chat/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/checkout/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../app/checkout/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customer-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer-admin">> = Specific
  const handler = {} as typeof import("../../../app/customer-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/danh-muc/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/danh-muc/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/danh-muc/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/danh-muc/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/danh-muc">> = Specific
  const handler = {} as typeof import("../../../app/danh-muc/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/du-an/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/du-an">> = Specific
  const handler = {} as typeof import("../../../app/du-an/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/lien-he/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/lien-he">> = Specific
  const handler = {} as typeof import("../../../app/lien-he/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/orders/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../app/orders/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/policies/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/policies">> = Specific
  const handler = {} as typeof import("../../../app/policies/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/products/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../app/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/projects/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/return-policy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/return-policy">> = Specific
  const handler = {} as typeof import("../../../app/return-policy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/search/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../app/search/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/services/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/services/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../app/services/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/support/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../app/support/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warranty/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/warranty">> = Specific
  const handler = {} as typeof import("../../../app/warranty/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wishlist/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/wishlist">> = Specific
  const handler = {} as typeof import("../../../app/wishlist/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
